CREATE TABLE "event-management-system_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event-management-system_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"description" text NOT NULL,
	"start_date" timestamp with time zone NOT NULL,
	"end_date" timestamp with time zone NOT NULL,
	"location" text NOT NULL,
	"type" text NOT NULL,
	"general_ticket_price" numeric(10, 2) NOT NULL,
	"vip_ticket_price" numeric(10, 2) NOT NULL,
	"vip_perks" text NOT NULL,
	"max_attendees" integer NOT NULL,
	"organizer_id" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "event-management-system_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event-management-system_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"type" text NOT NULL,
	"is_read" boolean DEFAULT false NOT NULL,
	"event_id" integer,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event-management-system_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event-management-system_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "event-management-system_registration" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event-management-system_registration_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"event_id" integer NOT NULL,
	"ticket_type" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"payment_status" text DEFAULT 'pending' NOT NULL,
	"total_amount" numeric(10, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "event-management-system_ticket" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event-management-system_ticket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"registration_id" integer NOT NULL,
	"ticket_number" text NOT NULL,
	"qr_code" text NOT NULL,
	"is_used" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event-management-system_user" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"name" text NOT NULL,
	"role" text DEFAULT 'user' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "event-management-system_event" ADD CONSTRAINT "event-management-system_event_organizer_id_event-management-system_user_id_fk" FOREIGN KEY ("organizer_id") REFERENCES "public"."event-management-system_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event-management-system_notification" ADD CONSTRAINT "event-management-system_notification_user_id_event-management-system_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."event-management-system_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event-management-system_notification" ADD CONSTRAINT "event-management-system_notification_event_id_event-management-system_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."event-management-system_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event-management-system_registration" ADD CONSTRAINT "event-management-system_registration_user_id_event-management-system_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."event-management-system_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event-management-system_registration" ADD CONSTRAINT "event-management-system_registration_event_id_event-management-system_event_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."event-management-system_event"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event-management-system_ticket" ADD CONSTRAINT "event-management-system_ticket_registration_id_event-management-system_registration_id_fk" FOREIGN KEY ("registration_id") REFERENCES "public"."event-management-system_registration"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "organizer_idx" ON "event-management-system_event" USING btree ("organizer_id");--> statement-breakpoint
CREATE INDEX "type_idx" ON "event-management-system_event" USING btree ("type");--> statement-breakpoint
CREATE INDEX "start_date_idx" ON "event-management-system_event" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "status_idx" ON "event-management-system_event" USING btree ("status");--> statement-breakpoint
CREATE INDEX "notification_user_idx" ON "event-management-system_notification" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "event_notification_idx" ON "event-management-system_notification" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "name_idx" ON "event-management-system_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_event_idx" ON "event-management-system_registration" USING btree ("user_id","event_id");--> statement-breakpoint
CREATE INDEX "event_idx" ON "event-management-system_registration" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "registration_status_idx" ON "event-management-system_registration" USING btree ("status");--> statement-breakpoint
CREATE INDEX "registration_idx" ON "event-management-system_ticket" USING btree ("registration_id");--> statement-breakpoint
CREATE INDEX "ticket_number_idx" ON "event-management-system_ticket" USING btree ("ticket_number");--> statement-breakpoint
CREATE INDEX "email_idx" ON "event-management-system_user" USING btree ("email");